### ISSUE TITLE
running code in lubuntu

### ISSUE THREAD

**Issue by maniksampath** [roothaxor/Ransom#1]

**Comment by roothaxor** [comment]
its basic of python you have to install dependencies which are imported in script, install it using 
command:  python pip or pip install pycrypto 
or download it manually: https://www.google.co.in/search?q=python crypto library 2.7

**Comment by maniksampath** [comment]
dear axor,

thanks for your reply whether it will run in lubuntu.for running which one
i need to run first pls tell me the order. decrypter.c and  encrpter.c
file is used for encrypting but what is the use of
batch_ransom_example.txt0,c2serverlist.txt.whether i need to install apache
web server.

**Comment by roothaxor** [comment]
it seems you got it wrong it is not all one ransomware code see readme.md, are parts of a rasomaware collected while forensics

**Comment by maniksampath** [comment]
dear roothaxor,

It is running in ludbuntu and it was showing indentation error in
holycrypt-v0.3.py the error message "  with open(OutputFile,"wb")as
outfile:IndentationError: expected an indented block". how to fix it pls
tell me.



On Sat, Feb 18, 2017 at 9:22 AM, manikandan s <manikandansampath28@gmail.com
> wrote:

> dear axor,
>
> thanks for your reply whether it will run in lubuntu.for running which one
> i need to run first pls tell me the order. decrypter.c and  encrpter.c
> file is used for encrypting but what is the use of
> batch_ransom_example.txt0,c2serverlist.txt.whether i need to install
> apache web server.
>

**Comment by maniksampath** [comment]
dear sanjay,

im having all the files in read me.whether still i need any files.

**Comment by maniksampath** [comment]
dear axor,

can u  help me, i am doing project in ransomware.what are the files i need
to run it.can u explain how to run because in readme file i cant able to
understand. Im not having that much knowledge in ransomware i am new to
this area.In my company they asked me to do research in this.....


On Sat, Feb 18, 2017 at 1:02 PM, manikandan s <manikandansampath28@gmail.com
> wrote:

> dear sanjay,
>
> im having all the files in read me.whether still i need any files.
>
> On Sat, Feb 18, 2017 at 12:42 PM, manikandan s <

**Comment by roothaxor** [comment]
Sure close this topic and connect on roothaxor@protonmail.com
