### ISSUE TITLE
Undefined reference

### ISSUE THREAD

**Issue by beeprime** [roothaxor/Ransom#2]
getting below errors upon compiling in MinGW (with openssl installed)

undefined reference to `EVP_aes_256_cbc'

undefined reference to `EVP_CipherInit'

undefined reference to `EVP_CIPHER_CTX_block_size'

undefined reference to `EVP_CipherUpdate'

undefined reference to `EVP_CipherFinal'

**Comment by roothaxor** [comment]
Code is dumped from Analysis hope you can understand
